In [31]:
import librosa
import numpy as np
import librosa.display 
import matplotlib.pyplot as plt


In [32]:
y, sr = librosa.load('65-orig_20201005-argumentdelivery.mp3', offset = 3552.67, duration = 3568.165 - 3552.67)

/opt/anaconda3/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


In [33]:
f0, voiced_flag, voiced_probs = librosa.pyin(y, fmin=librosa.note_to_hz('C2'), fmax=librosa.note_to_hz('C7'))
times = librosa.times_like(f0)
np.average(f0[np.isfinite(f0)])

159.18796406851763

In [34]:
f0

array([         nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan, 248.37216906, 325.8414615 ,
       327.72904189, 295.36595061, 293.66476792, 288.61978298,
       283.66146786, 285.30470202, 286.95745535, 290.29174037,
       290.29174037, 295.36595061, 298.79793764, 293.66476792,
       288.61978298, 286.95745535, 286.95745535, 285.30470202,
       285.30470202,          nan,          nan,          nan,
                nan,          nan, 156.464662  , 157.37105257,
       160.12185011, 168.66611791, 175.625645  , 178.6955272 ,
       177.6663167 , 204.08500573, 207.65234879, 207.65

In [36]:
#take log
log_f0 = np.log(f0)

In [37]:
log_f0

array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
       5.5149283 , 5.78641095, 5.79218718, 5.6882151 , 5.68243887,
       5.66511019, 5.64778151, 5.65355774, 5.65933397, 5.67088642,
       5.67088642, 5.6882151 , 5.69976755, 5.68243887, 5.66511019,
       5.65933397, 5.65933397, 5.65355774, 5.65355774,        nan,
              nan,        nan,        nan,        nan, 5.05283018,
       5.05860641, 5.07593509, 5.12792113, 5.16835471, 5.18568339,
       5.17990717, 5.3185366 , 5.33586528, 5.33586528, 5.33008905,
       5.32431283, 5.24922188, 5.15680226,        nan, 5.15680226,
       5.13369735, 5.1221449 , 5.1221449 , 5.11636867, 5.09903

In [38]:
#take diff of log
diff1_log_f0 = np.diff(log_f0)

In [39]:
diff1_log_f0

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
        0.27148265,  0.00577623, -0.10397208, -0.00577623, -0.01732868,
       -0.01732868,  0.00577623,  0.00577623,  0.01155245,  0.        ,
        0.01732868,  0.01155245, -0.01732868, -0.01732868, -0.00577623,
        0.        , -0.00577623,  0.        ,         nan,         nan,
               nan,         nan,         nan,         nan,  0.00577623,
        0.01732868,  0.05198604,  0.04043359,  0.01732868, -0.00577623,
        0.13862944,  0.01732868,  0.        , -0.00577623, -0.00577623,
       -0.07509094, -0.09241962,         nan,         nan, -0.02

In [40]:
#drop na
diff1_log_f0_dropna = diff1_log_f0[~np.isnan(diff1_log_f0)]

In [41]:
diff1_log_f0_dropna

array([ 0.27148265,  0.00577623, -0.10397208, -0.00577623, -0.01732868,
       -0.01732868,  0.00577623,  0.00577623,  0.01155245,  0.        ,
        0.01732868,  0.01155245, -0.01732868, -0.01732868, -0.00577623,
        0.        , -0.00577623,  0.        ,  0.00577623,  0.01732868,
        0.05198604,  0.04043359,  0.01732868, -0.00577623,  0.13862944,
        0.01732868,  0.        , -0.00577623, -0.00577623, -0.07509094,
       -0.09241962, -0.02310491, -0.01155245,  0.        , -0.00577623,
       -0.01732868, -0.01155245,  0.04620981,  0.04043359,  0.01732868,
        0.02310491,  0.02310491, -0.00577623, -0.04043359, -0.03465736,
       -0.04620981, -0.00577623,  0.00577623,  0.02310491, -0.06931472,
       -0.00577623, -0.02310491, -0.01732868, -0.01732868, -0.02310491,
       -0.00577623,  0.01155245,  0.        ,  0.        ,  0.        ,
       -0.01155245, -0.01155245,  0.01732868,  0.01155245,  0.00577623,
        0.        , -0.00577623, -0.01155245,  0.04043359, -0.00

In [42]:
np.average(diff1_log_f0_dropna)

-0.0035928681607971615

In [43]:
np.var(diff1_log_f0_dropna)

0.0016048846406993898